
export const detailsData = [
    {
        label: 'Product Details',
        long: "Beautya's 1st revitalizing serum that concentrates the double power of the Rose de Granville from the stem to the flower to revitalize the skin twice as fast (1) and visibly rejuvenate.<br/>Created after 20 years of research, the 10,000 (2) micro-pearls rich in revitalizing rose micro-nutrients are now completed by the power of the Rose sap. The next-generation, 92% natural-origin (3) formula of La Micro-Huile de Rose Advanced Serum is twice as concentrated,(4) combining the nourishing richness of an oil with the deep penetration of a serum.<br/><br/>From the first application of the serum, the skin appears plumped. In 3 weeks, 2x improvement in the look or feel of skin elasticity.(5) With regular use, skin looks and feels transformed.<br/><br/>As if replenished from within, the skin seems denser and firmer, and wrinkles appear noticeably reduced. As if lifted, facial contours appear enhanced.<br/><br/>Reveal your extraordinary beauty with Beautya Prestige.<br/><br/>(1) Instrumental test, 32 panelists, after 30 min.<br/>(2) In a 30 ml bottle.<br/>(3) Amount calculated based on the ISO 16128-1 and ISO 16128-2 standard. Water percentage included. The remaining 8% of ingredients contribute to the formula’s performance, sensory appeal and stability.<br/>(4) In Rose de Granville micro-nutrients compared to the previous formula.<br/>(5) Clinical assessment by a dermatologist on the evolution of the product’s performance on the skin elasticity, comparison between the effect after 7 days and 28 days on 34 women",
        short: "Beautya's 1st Revitalizing Serum That Concentrates The Double Power Of The Rose De Granville From The Stem To The Flower To Revitalize The Skin Twice As Fast (1) And Visibly Rejuvenate...",
        required: true,
    },
    {
        label: 'How To Apply',
        long: "Beautya's 1st revitalizing serum that concentrates the double power of the Rose de Granville from the stem to the flower to revitalize the skin twice as fast (1) and visibly rejuvenate.<br/>Created after 20 years of research, the 10,000 (2) micro-pearls rich in revitalizing rose micro-nutrients are now completed by the power of the Rose sap. The next-generation, 92% natural-origin (3) formula of La Micro-Huile de Rose Advanced Serum is twice as concentrated,(4) combining the nourishing richness of an oil with the deep penetration of a serum.<br/><br/>From the first application of the serum, the skin appears plumped. In 3 weeks, 2x improvement in the look or feel of skin elasticity.(5) With regular use, skin looks and feels transformed.<br/><br/>As if replenished from within, the skin seems denser and firmer, and wrinkles appear noticeably reduced. As if lifted, facial contours appear enhanced.<br/><br/>Reveal your extraordinary beauty with Beautya Prestige.<br/><br/>(1) Instrumental test, 32 panelists, after 30 min.<br/>(2) In a 30 ml bottle.<br/>(3) Amount calculated based on the ISO 16128-1 and ISO 16128-2 standard. Water percentage included. The remaining 8% of ingredients contribute to the formula’s performance, sensory appeal and stability.<br/>(4) In Rose de Granville micro-nutrients compared to the previous formula.<br/>(5) Clinical assessment by a dermatologist on the evolution of the product’s performance on the skin elasticity, comparison between the effect after 7 days and 28 days on 34 women",
        short: "Step 1: Dispense Two To Three Pumps Into The Palm Of Your Hand. Then, Using The Pads Of The Fingers, Apply The Serum To The Entire Face From The Centre Outwards.Step 2: Use Gentle Pressure To Make The Serum Penetrate Deeply..",
        required: true,
    },
    {
        label: 'Ingredient',
        long: "Beautya's 1st revitalizing serum that concentrates the double power of the Rose de Granville from the stem to the flower to revitalize the skin twice as fast (1) and visibly rejuvenate.<br/>Created after 20 years of research, the 10,000 (2) micro-pearls rich in revitalizing rose micro-nutrients are now completed by the power of the Rose sap. The next-generation, 92% natural-origin (3) formula of La Micro-Huile de Rose Advanced Serum is twice as concentrated,(4) combining the nourishing richness of an oil with the deep penetration of a serum.<br/><br/>From the first application of the serum, the skin appears plumped. In 3 weeks, 2x improvement in the look or feel of skin elasticity.(5) With regular use, skin looks and feels transformed.<br/><br/>As if replenished from within, the skin seems denser and firmer, and wrinkles appear noticeably reduced. As if lifted, facial contours appear enhanced.<br/><br/>Reveal your extraordinary beauty with Beautya Prestige.<br/><br/>(1) Instrumental test, 32 panelists, after 30 min.<br/>(2) In a 30 ml bottle.<br/>(3) Amount calculated based on the ISO 16128-1 and ISO 16128-2 standard. Water percentage included. The remaining 8% of ingredients contribute to the formula’s performance, sensory appeal and stability.<br/>(4) In Rose de Granville micro-nutrients compared to the previous formula.<br/>(5) Clinical assessment by a dermatologist on the evolution of the product’s performance on the skin elasticity, comparison between the effect after 7 days and 28 days on 34 women",
        short: "AQUA/WATER/EAU, C12-15 ALKYL BENZOATE, GLYCERYL STEARATE SE, BUTYLENE GLYCOL, GLYCERIN, OLUS OIL/VEGETABLE OIL/HUILE VÉGÉTALE, ISONONYL ISONONANOATE, CETYL ALCOHOL, ETHYLHEXYL PALMITATE, CYCLOPENTASILOXANE, DIMETHICONE, POLYESTER-7, PHENOXYETHANOL, NEOPENTYL GLYCOL DIHEPTANOATE, BUTYROSPERMUM PARKII (SHEA) BUTTER, STEARETH-21, AVENA SATIVA (OAT)...",
        required: true,
    },
    {
        label: 'What Makes It Advance',
        long: "Beautya's 1st revitalizing serum that concentrates the double power of the Rose de Granville from the stem to the flower to revitalize the skin twice as fast (1) and visibly rejuvenate.<br/>Created after 20 years of research, the 10,000 (2) micro-pearls rich in revitalizing rose micro-nutrients are now completed by the power of the Rose sap. The next-generation, 92% natural-origin (3) formula of La Micro-Huile de Rose Advanced Serum is twice as concentrated,(4) combining the nourishing richness of an oil with the deep penetration of a serum.<br/><br/>From the first application of the serum, the skin appears plumped. In 3 weeks, 2x improvement in the look or feel of skin elasticity.(5) With regular use, skin looks and feels transformed.<br/><br/>As if replenished from within, the skin seems denser and firmer, and wrinkles appear noticeably reduced. As if lifted, facial contours appear enhanced.<br/><br/>Reveal your extraordinary beauty with Beautya Prestige.<br/><br/>(1) Instrumental test, 32 panelists, after 30 min.<br/>(2) In a 30 ml bottle.<br/>(3) Amount calculated based on the ISO 16128-1 and ISO 16128-2 standard. Water percentage included. The remaining 8% of ingredients contribute to the formula’s performance, sensory appeal and stability.<br/>(4) In Rose de Granville micro-nutrients compared to the previous formula.<br/>(5) Clinical assessment by a dermatologist on the evolution of the product’s performance on the skin elasticity, comparison between the effect after 7 days and 28 days on 34 women",
        short: "OVER 11 AWARDS WON! BIONYMPH PEPTIDE: Peptide Blend That Helps To Condition For Smoother, Plumper Looking Skin VITAMINS C & E: Work In Harmony To BRIGHTEN The Look Of Your Complexion And EVEN The Appearance Of The Skin Tone...",
        required: true,
    },
    {
        label: 'Product Specification',
        long: "Beautya's 1st revitalizing serum that concentrates the double power of the Rose de Granville from the stem to the flower to revitalize the skin twice as fast (1) and visibly rejuvenate.<br/>Created after 20 years of research, the 10,000 (2) micro-pearls rich in revitalizing rose micro-nutrients are now completed by the power of the Rose sap. The next-generation, 92% natural-origin (3) formula of La Micro-Huile de Rose Advanced Serum is twice as concentrated,(4) combining the nourishing richness of an oil with the deep penetration of a serum.<br/><br/>From the first application of the serum, the skin appears plumped. In 3 weeks, 2x improvement in the look or feel of skin elasticity.(5) With regular use, skin looks and feels transformed.<br/><br/>As if replenished from within, the skin seems denser and firmer, and wrinkles appear noticeably reduced. As if lifted, facial contours appear enhanced.<br/><br/>Reveal your extraordinary beauty with Beautya Prestige.<br/><br/>(1) Instrumental test, 32 panelists, after 30 min.<br/>(2) In a 30 ml bottle.<br/>(3) Amount calculated based on the ISO 16128-1 and ISO 16128-2 standard. Water percentage included. The remaining 8% of ingredients contribute to the formula’s performance, sensory appeal and stability.<br/>(4) In Rose de Granville micro-nutrients compared to the previous formula.<br/>(5) Clinical assessment by a dermatologist on the evolution of the product’s performance on the skin elasticity, comparison between the effect after 7 days and 28 days on 34 women",
        short: "Product Code-46000701 Key Ingredients-Hyaluronic Acid, Vitamin C Beauty Effect-Brightening...",
        required: true,
    },
]

export interface DetailsData {
    label: string;
    long: string;
    short: string;
    required: boolean;
}[]